artifacts_root: artifacts

data_injection: 
  dir_root: artifacts/data_injection
  file_location: /home/leksman/Downloads/Plant_Vilage_dataset
  main_data: artifacts/data_injection/dataset



model_trainer:
  dir_root: artifacts/model_trainer
  train_data_root: artifacts/data_injection/dataset/Plant_Vilage_dataset/train_test_data/PLATE_train
  trained_model: artifacts/model_trainer/cnn_model.pth
